### ISSUE TITLE
Speed of functions

### ISSUE THREAD

**Issue by lrfreeman** [kemerelab/ghostipy#4]
I have a time series vector of mV recordings from the HPC I'd like to analyse with your package. My hardware collected data at 20kHz and I have a vector of length = 23,987,540. Even when I downsample this vector to 200 Hz of length = 239,876 functions such as gsp.mtm_spectrum(channel_1, fs = 200, bandwidth=bandwidth, n_fft_threads=8) do not complete. Well atleast not within a few minutes. My colleague is using Chronux which works across many channels within 5 minutes at a higher frequency. I'm looking at a single channel for a lower sampling rate and it's not completing at a similar time period. Only when looking at a few samples is the example rapid. The example length of 250 was provided in the notebook. But my data size is exponentially larger. Perhaps I'm missing something but could you advise on how to speed these functions up?

`#My libraries
from utils import reshape

#Open Source Libraries
import ghostipy as gsp
import numpy as np
import matplotlib.pyplot as plt
import time

# Performance checks
start_time = time.time()

#Load and shape data
file = "/Users/freeman/Documents/saleem_lab/data/R21011_210915_CA1_1.dat"
data_object = reshape.Import_and_Shape_Data(file)
data = data_object.reshape_binary_data()

#Parameters
fs = 200 #hz
downsample = 2000 #hz 2khz is the goal
tw = 2 #transition window. How many hertz the filter crosses
power = 2 #Power to which the spline transition band functions are raised.
bandwidth = 15 #For multitaper

#Downsample and channel selection
print('Before downsampling', len(data[:, 0]))
print('After  downsampling', len(data[0:-1:100, 0]))
c1 = data[0:-1: 100, 0] #downsampled to speed up multi tapered estimation

#Computes the spectrum using Thomson's multitaper method
psd, freqs = gsp.mtm_spectrum(c1, fs = 200, bandwidth=bandwidth, n_fft_threads=8)
plt.plot(freqs, psd)

#How long did the full script take?
print("")
print("--- %s seconds ---" % (time.time() - start_time))
print("")

plt.show()`

**Comment by jchutrue** [comment]
Thanks for the issue. There could be several explanations for this, and I am investigating. Would you mind listing the parameters your colleague is using (Number of channels, number of samples of each channel, sampling rate, bandwidth)? How long is the computation time on their data?

**Comment by lrfreeman** [comment]
Thanks for your response. My colleague is running 62 channels, 20kHZ, data of length = 23,987,540, looking at 0-300hz using a low pass filter. Apparently in Chronux this takes 5 minutes. If I use 1 channel and downsample that one channel down to 200hz I still can't get gsp.mtm_spectrum() to complete. I'm running on the new Macbook pro. I have access to a GPU machine if needed.

**Comment by jchutrue** [comment]
I think I understand the problem but want to clarify something. With the specified bandwidth (15 Hz) and data window length (23,987,540 samples), you are computing 35980 tapers. That's where the process is getting stuck. 

Is your colleague using `NW` as their parameterization for Chronux? If so, many fewer tapers would need to be computed, and that would explain the performance difference.

**Comment by lrfreeman** [comment]
Hi thanks for your speedy response. Yes my colleague is imputting [NW, K] into Chronux function mtspectrumc. Where NW is the time-bandwidth product and K is the number of tapers to use. Specifically he's inputting [3, 5]. I tried using num_tapers = 5 for gsp.mtm_spectrum() but the process still does not complete. Do you have any advice?

Thanks,

Laurence

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jchutrue** [comment]
Using that value of `NW` there will be very little smoothing. You can see my calculation in the source code:
https://github.com/kemerelab/ghostipy/blob/e931e7553409e999c168074365a7700c8ff83171/ghostipy/spectral/mtm.py#L40

Therefore the bandwidth value you need for your data is `3*20000/23987540`. Try that and see how it goes.

**Comment by lrfreeman** [comment]
Hi Josh, 

Great thanks for your help that worked. The number of tapers estimated was large which I think influnced the processing time. Based on the examples I was trying bandwidth values of 10-20hz but really I needed values sub 1hz. Even 0.1 would take 10 minutes to complete. Which is strange right I thought a lower BW would increase computational time so I clearly don't understand one of the computations. I also managed to smooth the PSD by increasing NW proportionally to the number of tapers. So now my chart looks almost identical to my colleagues who is using Chronux.

<img width="594" alt="Screenshot 2022-01-19 at 17 11 33" src="https://user-images.githubusercontent.com/22481774/150185078-69f7e938-2b90-4b9a-908c-fb21c8ac0793.png">

I'll probably reach out in the next few days as I've having difficulties with the spectrograms. Let me know if you want my code to produce the PSD as a result of your help. Thanks again.

L
